### ISSUE TITLE
Installed Julia binaries obstruct system-installed ones

### ISSUE THREAD

**Issue by christopher-dG** [rofinn/Playground.jl#56]
If you prepend `$PATH` with the Playground bin directory as is suggested, `which julia` outputs the Playground binary even when the playground is not activated. This can be fixed by either moving the installed Julia binaries to some other directory (and then adding that to `$PATH` with `playground activate`) or just changing the suggested `$PATH` in the documentation to be appended instead. 

Observed on MacOS.  

e: Another solution that I think is much better is installing the `playground` executable to the user's local bin directory (`~/.local/bin`) or its equivalent) and then not adding `~/.playground/bin` to the path at all except when activating a playground.

**Comment by rofinn** [comment]
Hmm, this was the desired behaviour because I only use the julia binaries installed via playground. I suppose reversing the suggest `$PATH` modification would be fine.
