### ISSUE TITLE
Prepend to shell prompt after activation

### ISSUE THREAD

**Issue by christopher-dG** [rofinn/Playground.jl#59]
`virtualenv` converts the shell prompt to `(venvname) $PROMPT` at activation, which is really nice for knowing when you are/aren't in a virtualenv. I think it would be good for Playground to behave similarly.

e: I see this actually works nicely on bash, it does not on zsh though. It would be good for them to say the name of the active playground though!

**Comment by rofinn** [comment]
I know it already does this for bash, fish and in the REPL, but I don't use zsh so fixes on that front would be much appreciated.
