### ISSUE TITLE
if ENV["PATH"] contains spaces, playground rc script breaks

### ISSUE THREAD

**Issue by goretkin** [rofinn/Playground.jl#78]
Would be fixed by quoting some strings here
https://github.com/rofinn/Playground.jl/blob/0dc4bd60db076a04ef7cffa57c6688d83259aedb/src/shells/bash.jl#L21-L23

**Comment by rofinn** [comment]
Thanks. If you do `Pkg.checkout("Playground", "rf/shell-quoting")` does that fix your issue?

**Comment by goretkin** [comment]
works for me! thanks
